pdn/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'pdn.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'workshops.views.inschrijven', name='inschrijven'),

    url(r'^admin/', include(admin.site.urls)),
]

workshops/models.py
from django.db import models

# Create your models here.
class Workshop(models.Model):
    naam = models.CharField(max_length=64, unique=True, blank=False)
    min = models.IntegerField(default=0)
    max = models.IntegerField()
    hidden = models.BooleanField(default=False)

    def __str__(self):
        return self.naam.encode('utf-8')

class User(models.Model):
    naam = models.CharField(max_length=100, unique=True)
    email = models.CharField(max_length=100, blank=True)
    deleted = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.naam.encode('utf-8')

class WorkshopRating(models.Model):
    workshop = models.ForeignKey(Workshop)
    user = models.ForeignKey(User)
    rating = models.IntegerField(default=0)

workshops/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.core.exceptions import PermissionDenied

from models import Workshop, User, WorkshopRating

# Create your views here.
def inschrijven(request):
	workshops = list(Workshop.objects.all())
	if request.method == 'POST':
		user = User()
		user.naam = request.POST['naam']
		user.email = request.POST['email']
		user.save()
		for ws in workshops:
			rating = WorkshopRating()
			rating.workshop = ws
			rating.user = user
			rating.rating = request.POST['workshop_%s' % ws.id]
			rating.save()
		return render_to_response('complete.html', {}, context_instance=RequestContext(request))
	return render_to_response('inschrijven.html', {'workshops': workshops}, context_instance=RequestContext(request))

pdn/workshops/templates/inschrijven.html
{% extends "base.html" %}

{% block body %}
<h1>Inschrijven voor de workshops</h1>
Geef hieronder je voorkeuren voor de workshops morgenmiddag. Als je een workshop heel graag wil doen geef je hem een vijf, als je iets absoluut niet wil doen geef je het -5. Je kunt ook de cijfers ertussen gebruiken om je voorkeuren tussen de workshops aan te geven.<br>
We proberen rekening te houden met iedereens voorkeuren, maar om dat perfect te doen is helaas onmogelijk.
<form method="POST">
<table>
	<tr>
		<td><label for="id_naam">Naam</label></td>
		<td><input type="text" id="id_naam" name="naam" autocomplete="off" /></td>
	</tr>
	<tr>
		<td><label for="id_email">E-mail</label></td>
		<td><input type="text" id="id_email" name="email" autocomplete="off" /></td>
	</tr>
{% for ws in workshops %}
	<tr>
		<td><label for="id_{{ ws.id }}">{{ ws.naam }}</label></td>
		<td><select id="id_{{ ws.id }}" name="workshop_{{ ws.id }}">
			<option value="-5">-5</option>
			<option value="-4">-4</option>
			<option value="-3">-3</option>
			<option value="-2">-2</option>
			<option value="-1">-1</option>
			<option value="0" selected>0</option>
			<option value="1">1</option>
			<option value="2">2</option>
			<option value="3">3</option>
			<option value="4">4</option>
			<option value="5">5</option>
		</select></td>
	</tr>
{% endfor %}
	<tr>
		<td></td>
		<td><input type="submit" value="Inschrijven"></td>
	</tr>
</table>
</form>
{% endblock %}

workshops/templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<title>Pluk de Nacht &ndash; workshops</title>
		<link href="{{ MEDIA_URL }}style.css" rel="stylesheet" type="text/css" />
		<script type="text/javascript">
			{% block javascript %}{% endblock %}
		</script>
		<style>
body {
	font-family: "Droid Sans", "Open Sans", sans-serif;
	color: #111;
	max-width: 900px;
	margin: 0 auto;
}

table {
	margin: 0.75em 0;
}

td {
	padding: 1px 2em;
}
		</style>
		{% block head %}{% endblock %}
	</head>
	<body{% block bodyattrs %}{% endblock %}>
		<div id="wrapper">
			<div id="header">
				<!-- <img src="{{ MEDIA_URL }}logo.png"> -->
			</div>
{% if messages %}
			<ul class="messages">
	{% for message in messages %}
				<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
	{% endfor %}
			</ul>
{% endif %}
			<div id="content">
				{% block body %}{% endblock %}
			</div>
			{% block footer %}{% endblock %}
		</div>
	</body>
</html>

workshops/templates/complete.html
{% extends "base.html" %}
{% block head %}
<meta http-equiv="refresh" content="5; URL=/">
{% endblock %}

{% block body %}
<h1>Subscribing for workshops</h1>
<p>Thanks for subscribing!</p>
<a href="/">Next subscription</a>
{% endblock %}

workshops/templates/inschrijven.html
{% extends "base.html" %}

{% block body %}
<h1>Subscribing for workshops</h1>
<p>
	Please give your preferences for the workshop for tomorrow afternoon.
	If you really like to do a workshop then yank the thing to the right (10).
	Pull workshops that sound stupid to the left. Leave it in the middle if you
	don't care.
</p>
<p>
	We try to devide you as good as possible, but it turns out that it is really (NP) hard to do this perfectly.
</p>
<form method="post">
{% csrf_token %}
<table>
	<tr>
		<td><label for="id_naam">Name</label></td>
		<td><input type="text" id="id_naam" name="naam" autocomplete="off" /></td>
	</tr>
	<tr>
		<td><label for="id_email">Email</label></td>
		<td><input type="text" id="id_email" name="email" autocomplete="off" /> <small>(optional)</small></td>
	</tr>
{% for ws in workshops %}
	<tr{% if ws.hidden %} style="display: none;"{% endif %}>
		<td><label for="id_{{ ws.id }}">{{ ws.naam }}</label></td>
		<td>
			<em>lame!</em>
			<input id="id_{{ ws.id }}" name="workshop_{{ ws.id }}" type="range" value="0" min="-10" max="10" />
			<em>awesome!</em>
		</td>
	</tr>
{% empty %}
<tr>
	<td></td>
	<td>
		<em>Fail! The system knows no workshops yet.</em>
	</td>
</tr>
{% endfor %}
	<tr>
		<td></td>
		<td><input type="submit" value="Submit preferences :D"></td>
	</tr>
</table>
</form>
{% endblock %}